apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: scalex-project-template-target-annotations
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      labelSelector:
        matchLabels:
          scalex.io/project: scalex-project-template
  overrideRules:
    - targetCluster:
        labelSelector:
          matchExpressions:
            - key: scalex.io/role
              operator: In
              values:
                - child
            - key: scalex.io/topology
              operator: In
              values:
                - baremetal
            - key: scalex.io/site
              operator: In
              values:
                - b
                - c
      overriders:
        plaintext:
          - path: /metadata/annotations/scalex.io~1federation-managed
            operator: add
            value: "true"
