apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: scalex-child-baremetal-example
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      namespace: scalex-federation-examples
      name: scalex-federation-example-placeholder
  placement:
    clusterAffinity:
      labelSelector:
        matchExpressions:
          - key: scalex.io/role
            operator: In
            values:
              - child
          - key: scalex.io/topology
            operator: In
            values:
              - baremetal
          - key: scalex.io/site
            operator: In
            values:
              - b
              - c
