examplePolicies:
  enabled: false

memberSelector:
  role: child
  topology: baremetal
  sites:
    - b
    - c

examples:
  propagation:
    name: scalex-child-baremetal-example
    resourceSelector:
      apiVersion: v1
      kind: ConfigMap
      namespace: scalex-federation-examples
      name: scalex-federation-example-placeholder
  override:
    name: scalex-child-baremetal-example
    resourceSelector:
      apiVersion: v1
      kind: ConfigMap
      namespace: scalex-federation-examples
      name: scalex-federation-example-placeholder
    annotationKey: scalex.io/federation-example
    annotationValue: disabled-by-default
